# Generated by Django 3.1.3 on 2020-12-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201220_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='inicio',
            field=models.DateField(verbose_name='Início'),
        ),
    ]
